# General settings
scene_name: "blender_scene"
output_dir: "./outputs/${scene_name}"
checkpoint_dir: "${output_dir}/checkpoints"
transforms_json: "transforms_${scene_name}.json"
rays_file: "${scene_name}_ray_data.npz"

# resize images
# python scripts\resize_images.py
workspace: data/${scene_name}
img_dir_original: ${workspace}/images_original
new_images_dir: ${workspace}/images
newSize: [512, 512] # 1024 / 2

# transform.json
# python scripts\normalize_with_aabb.py
rotation: True
rotation_initial: #null
  - [0.77892503, -0.25715966, 0.57196565]
  - [-0.62710305, -0.32549969, 0.70766639]
  - [0.00419140, -0.90990047, -0.41480546]

#compute_percentile_bbox(points, lower=1.0, upper=99.8, padding=0.17)
percentile_bbox:
  lower: 1.0
  upper: 99.8
  padding: 0.17

rot_order: [0, 1, 2] # apply order rotation
# axis order x, y, z - alpha, beta, gamma
angles: [75, 0, 0] # alpha, beta, gamma
shift: [-0.1, -0.2, -0.3]
visualize: True

# aabb
aabb_adjust:
  aabb_min: [0, 0, 0.85]
  aabb_max: [0, 0, 0.1]

# slicing
aabb_slice: True
vol_extracted_dir: "blender_final.pth"
sliced_vol_path: colored_occupancy_${scene_name}_sliced.pth

# colamp -> transforms.json
colmap_dir: "./data/${scene_name}"

# Training options
batch_size: 4096 # 2048 # 1024
num_epochs: 20 #10
lr: 0.0005

# Model options
nerf_type: large
ngp: true
hidden_dim: 256
pos_L: 10
dir_L: 4

# Rendering options
N_samples: 64
N_importance: 128
white_bg: false
chunk_size: 32768
use_memmap: False
